### ISSUE TITLE
Combine GitHub action OS jobs

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#237]
We have two jobs defined, one for Linux and one for OS X, both in the test workflow and in the tagged-release workflow. Most steps are the same. We should just combine them and have the steps that differ be conditioned on the OS.

I think one can do like:
```yaml
  steps:
    - name: foo
      if: runner.os == 'Linux'
```
or somesuch. This will also look nicer when we start doing multiple versions of each OS.
